server:
   port: 4000

DB:
   type: 'postgres'
   port: 5432
   database: 'postgres'
   host: "18.214.236.253"
   username: 'icpostgresql'
   password: '7d2fc198087efb162b821d6704b18182'
   synchronize: true

redis:
  host: '54.68.182.224'
  port: 6379
  password: 'b61023583ec444cb'
  username: 'icredis'

jwt:
   secret: 'jwtsecrethere'
   expiresIn: 7200

mail:
   user: 'noreply@scoop.love'
   pass: '9VmV66Z7u5zzfNq'
   host: 'ecngx264.inmotionhosting.com'
   port: '465'