server:
   port: 4000

DB:
   type: 'postgres'
   port: 5432
   database: 'postgres'
   host: "3.133.209.250"
   username: 'icpostgresql'
   password: '7175a5c3d7f94ea7'
   synchronize: true

redis:
  host: '18.218.140.148'
  port: 6379
  password: 'b61023583ec444cb'
  username: 'icredis'

jwt:
   secret: 'jwtsecrethere'
   expiresIn: 7200

mail:
   user: 'noreply@scoop.love'
   pass: '9VmV66Z7u5zzfNq'
   host: 'ecngx264.inmotionhosting.com'
   port: '465'