name: Build and deploy Node.js app to Azure Container Registry - scoopDevContainerRegistry

on:
    push:
        branches:
            - development
            - main

jobs:

    deploy-dev:
        runs-on: ubuntu-latest
        needs: build-dev
        if: github.ref == 'refs/heads/development'

        steps:
            - name: Set up Python and Azure CLI
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

            - name: Deploy to Azure Container Instances (Development)
              uses: azure/aci-deploy@v1
              with:
                  resource-group: scoop-dev-rg
                  dns-name-label: scoop-dev.h4atavatenajbtd5.eastus.azurecontainer.io
                  name: backend
                  image: ${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_DEV }}/backend:latest
                  registry-login-server: ${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_DEV }}
                  registry-username: ${{ vars.AZURE_CONTAINER_REGISTRY_USERNAME_DEV }}
                  registry-password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD_DEV }}
                  os-type: Linux
                  cpu: 1
                  memory: 1.5
                  location: eastus

    deploy-prod:
        runs-on: ubuntu-latest
        needs: build-prod
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Set up Python and Azure CLI
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

            - name: Deploy to Azure Container Instances (Production)
              uses: azure/aci-deploy@v1
              with:
                  resource-group: scoop-prod-rg
                  dns-name-label: prod-backend
                  name: backend
                  image: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_PROD }}/backend:${{ github.sha }}
                  registry-login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_PROD }}
                  registry-username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME_PROD }}
                  registry-password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD_PROD }}
                  os-type: Linux
                  cpu: 1
                  memory: 1.5
                  location: eastus
