name: Build and Deploy to dev

on:
  push:
    branches:
      - development
#env:
  #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #AWS_DEFAULT_REGION: 'us-east-1'
  #AWS_SECRETS_BUCKET_NAME: ${{ secrets.AWS_SECRETS_BUCKET_NAME }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2   
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Download private key from S3
        run: aws s3 cp s3://${{ secrets.AWS_SECRETS_BUCKET_NAME }}/privateKeys/backend_Service_graphql.pem  backend_Service_graphql.pem
               
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
            ssh -o StrictHostKeyChecking=no -i backend_Service_graphql.pem ec2-user@ec2-54-242-81-114.compute-1.amazonaws.com 
            cd /var/www/backend
            git pull origin main            
            echo "Pulling recent changes from repo"

      - name: install dependencies
        run: |
          echo "Installing dependencies"
          npm install

      - name: build
        run: |
          npm run build && pm2 restart 0
           echo "Completed!!"
