name: Build and Deploy to dev

on:
  push:
    branches:
      - development
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_SECRETS_BUCKET_NAME: ${{ secrets.AWS_SECRETS_BUCKET_NAME }}
  AWS_S3_BUILD_ARTIFACTS_BUCKET_NAME: ${{ secrets.AWS_S3_BUILD_ARTIFACTS_BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: pull code
        uses: actions/checkout@v3
      - name: srt up node.js nevironment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: pull secrets
        run: |
          aws s3 sync "s3://$AWS_SECRETS_BUCKET_NAME" .
          mv scoop-backend/.env .
          rm -rf scoop-backend
      - name: install dependencies
        run: |
          npm install
      - name: build
        run: |
          npm run build
      - name: build artifacts as zip
        run: |
          echo "Creating build artifacts as zip"
          zip -qr scoop-backend-dev.zip .
          echo "Completed!!"
      - name: Upload artifacts to S3
        run: |
          aws s3 cp scoop-backend-dev.zip "s3://$AWS_S3_BUILD_ARTIFACTS_BUCKET_NAME"
      # - name: Deploy aftifacts to EC2
      #   run: |
      #     #versionLabel=$(uuidgen)
      #     aws elasticbeanstalk create-application-version --application-name scoop-backend-prod --source-bundle S3Bucket="$AWS_S3_BUILD_ARTIFACTS_BUCKET_NAME",S3Key="scoop-backend-prod.zip" --version-label="$versionLabel"
      #     aws elasticbeanstalk update-environment --application-name scoop-backend-prod --environment-name Scoopbackendprod-env --version-label "$versionLabel"
      - name: Deploy to EC2 with CodeDeploy
        run: |          
          aws s3 cp scoop-backend-dev.zip s3://$AWS_S3_BUILD_ARTIFACTS_BUCKET_NAME/scoop-backend-dev.zip
          aws deploy create-deployment --application-name backend-dev-app --deployment-group-name ec2-backend-dev-app --s3-location bucket=$AWS_S3_BUILD_ARTIFACTS_BUCKET_NAME,key=scoop-backend-dev.zip,bundleType=zip --deployment-config-name CodeDeployDefault.AllAtOnce
           