name: Build and deploy Node.js app to scoopProdContainerRegistry

on:
    push:
        branches:
            - main

jobs:
    build-prod:
        runs-on: ubuntu-latest
        if: github.ref_name == 'main'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Print DB_SSL_CA_CERT_DEV
              run: echo ${{ secrets.DB_SSL_CA_CERT_DEV }}

            - name: Set secrets as build arguments
              env:
                  DB_TYPE: ${{ vars.DB_TYPE_PROD }}
                  DB_DATABASE: ${{ vars.DB_DATABASE_PROD }}
                  DB_HOST: ${{ vars.DB_HOST_PROD }}
                  DB_USERNAME: ${{ vars.DB_USERNAME_PROD }}
                  DB_PORT: ${{ vars.DB_PORT_PROD }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD_PROD }}
                  DB_SSL_CA_CERT: ${{ secrets.DB_SSL_CA_CERT_PROD }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET_PROD }}
                  JWT_EXPIRES_IN: ${{ vars.JWT_EXPIRES_IN_PROD }}
                  PORT: ${{ vars.PORT_PROD }}
                  FILESERVICE_PORT: ${{ vars.FILESERVICE_PORT_PROD }}
                  BE_FILE_SERVER_URL: ${{ vars.BE_FILE_SERVER_URL_PROD }}
              run: |
                  echo "DB_TYPE=${DB_TYPE}" >> $GITHUB_ENV
                  echo "DB_DATABASE=${DB_DATABASE}" >> $GITHUB_ENV
                  echo "DB_HOST=${DB_HOST}" >> $GITHUB_ENV
                  echo "DB_USERNAME=${DB_USERNAME}" >> $GITHUB_ENV
                  echo "DB_PORT=${DB_PORT}" >> $GITHUB_ENV
                  echo "DB_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV
                  echo "DB_SSL_CA_CERT=${DB_SSL_CA_CERT}" >> $GITHUB_ENV
                  echo "JWT_SECRET=${JWT_SECRET}" >> $GITHUB_ENV
                  echo "JWT_EXPIRES_IN=${JWT_EXPIRES_IN}" >> $GITHUB_ENV
                  echo "PORT=${PORT}" >> $GITHUB_ENV
                  echo "FILESERVICE_PORT=${FILESERVICE_PORT}" >> $GITHUB_ENV
                  echo "BE_FILE_SERVER_URL=${BE_FILE_SERVER_URL}" >> $GITHUB_ENV

            - name: Print env variables
              run: |
                  echo "DB_TYPE=$DB_TYPE" 
                  echo "DB_DATABASE=$DB_DATABASE"
                  echo "DB_HOST=$DB_HOST"
                  echo "DB_USERNAME=$DB_USERNAME"
                  echo "DB_PORT=$DB_PORT"
                  echo "DB_PASSWORD=$DB_PASSWORD"
                  echo "DB_SSL_CA_CERT=$DB_SSL_CA_CERT"
                  echo "JWT_SECRET=$JWT_SECRET"
                  echo "JWT_EXPIRES_IN=$JWT_EXPIRES_IN"
                  echo "PORT=$PORT"
                  echo "FILESERVICE_PORT=${FILESERVICE_PORT}"
                  echo "BE_FILE_SERVER_URL=$BE_FILE_SERVER_URL"

            - uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - uses: azure/docker-login@v1
              with:
                  login-server: ${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_PROD }}
                  username: ${{ vars.AZURE_CONTAINER_REGISTRY_USERNAME_PROD }}
                  password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD_PROD }}

            - name: Build and push Docker image (Production)
              run: |
                  docker build -t ${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_PROD }}/backend:${{ github.sha }} -f Dockerfile.prod --build-arg DB_TYPE="${DB_TYPE}" --build-arg DB_DATABASE="${DB_DATABASE}" --build-arg DB_HOST="${DB_HOST}" --build-arg DB_USERNAME="${DB_USERNAME}" --build-arg DB_PORT="${DB_PORT}" --build-arg DB_PASSWORD="${DB_PASSWORD}" --build-arg DB_SSL_CA_CERT="${DB_SSL_CA_CERT}" --build-arg JWT_SECRET="${JWT_SECRET}" --build-arg JWT_EXPIRES_IN="${JWT_EXPIRES_IN}" --build-arg PORT="${PORT}" --build-arg BE_FILE_SERVER_URL="${BE_FILE_SERVER_URL}" .
                  docker push ${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_PROD }}/backend:${{ github.sha }}
                  docker build -t ${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_PROD }}/backend:latest -f Dockerfile.prod --build-arg DB_TYPE="${DB_TYPE}" --build-arg DB_DATABASE="${DB_DATABASE}" --build-arg DB_HOST="${DB_HOST}" --build-arg DB_USERNAME="${DB_USERNAME}" --build-arg DB_PORT="${DB_PORT}" --build-arg DB_PASSWORD="${DB_PASSWORD}" --build-arg DB_SSL_CA_CERT="${DB_SSL_CA_CERT}" --build-arg JWT_SECRET="${JWT_SECRET}" --build-arg JWT_EXPIRES_IN="${JWT_EXPIRES_IN}" --build-arg PORT="${PORT}" --build-arg BE_FILE_SERVER_URL="${BE_FILE_SERVER_URL}" .
                  docker push ${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_PROD }}/backend:latest

    deploy-prod:
        runs-on: ubuntu-latest
        needs: build-prod
        if: github.ref_name == 'main'

        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Set up Python and Azure CLI
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

            - uses: azure/aks-set-context@v3
              with:
                  resource-group: scoop-prod-rg
                  cluster-name: scoop-prod-kubernetes
            - name: Setup kubectl
              uses: azure/setup-kubectl@v1
              id: install

            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Substitute environment variables in k8s config
              run: |
                  export PORT=${{ vars.PORT_PROD }}
                  export FILESERVICE_PORT=${{ vars.FILESERVICE_PORT_PROD }}
                  export IMAGE_TAG=${{ github.sha }}
                  export CONTAINER_REGISTRY=${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_PROD }}
                  touch k8/k8.yml
                  envsubst < k8/k8.yml.template > k8/k8.yml

            - name: Echo contents of k8.yml
              run: cat k8/k8.yml
              
            - name: Deploy to AKS
              id: deploy-aks
              uses: Azure/k8s-deploy@v4
              with:
                  namespace: 'default'
                  manifests: |
                      k8/k8.yml
