# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - facets-dev-backend-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://scoopdevcontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_caa87d685c664acfb02a3917d39a2954 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_59a8171f65224bbeaf3d7b4236f92b69 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: scoopdevcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_caa87d685c664acfb02a3917d39a2954 }}/backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'facets-dev-backend-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a8324c9d3d2340ac8843eb73765376fb }}
        images: 'scoopdevcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_caa87d685c664acfb02a3917d39a2954 }}/backend:${{ github.sha }}'